In [ ]:
!pip install torch torchvision torchaudio

In [3]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU count:", torch.cuda.device_count())

PyTorch version: 2.10.0+cpu
CUDA available: False
GPU count: 0


In [4]:
import torch

# 直接创建
x = torch.tensor([1,2,3])
print(x)

# 创建矩阵
A = torch.tensor([[1,2],[3,4]])
print(A)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


In [6]:
torch.zeros(3,3)      # 全0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,4)       # 全1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.rand(3,3)       # 随机数

tensor([[0.1575, 0.3121, 0.6576],
        [0.0963, 0.8547, 0.3835],
        [0.6874, 0.6617, 0.3156]])

In [9]:
torch.randn(3,3)      # 正态分布

tensor([[-0.3467,  1.0615,  1.8705],
        [-0.4425, -0.4783, -1.4010],
        [ 1.0403, -0.1691, -0.2799]])

In [10]:
torch.eye(3)          # 单位矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
x = torch.rand(3,4)

print(x.shape)     # 维度
print(x.dtype)     # 数据类型
print(x.device)    # 设备

torch.Size([3, 4])
torch.float32
cpu


In [12]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [13]:
A = torch.tensor([[1.,2.],
                  [3.,4.]])

B = torch.tensor([[5.,6.],
                  [7.,8.]])

C = torch.matmul(A,B)

print(C)

tensor([[19., 22.],
        [43., 50.]])


In [14]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [15]:
x[0,1]

tensor(2)

In [16]:
x[1]

tensor([4, 5, 6])

In [17]:
x[:,1]

tensor([2, 5, 8])

In [18]:
x[0:2,1:3]

tensor([[2, 3],
        [5, 6]])

In [20]:
x = torch.arange(12)
print(x)

x = x.reshape(3,4)

print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [21]:
x.flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
x.unsqueeze(0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [23]:
x.squeeze()

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [24]:
x = torch.tensor([1.,2.,3.,4.])

In [27]:
print ("mean:", torch.mean(x))
print ("sum: ", torch.sum(x))
print ("max: ", torch.max(x))
print ("min: ", torch.min(x))
print ("std: ",torch.std(x))

mean: tensor(2.5000)
sum:  tensor(10.)
max:  tensor(4.)
min:  tensor(1.)
std:  tensor(1.2910)


In [31]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2 + 3*x + 1
y.backward()
print(x.grad)

tensor(7.)
